#pragma config(Sensor, S2,     leftbutton,     sensorEV3_Touch)
#pragma config(Sensor, S3,     rightbutton,    sensorEV3_Touch)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int SPIRAL = 1;
	int WALLFOLLOW = 2;
	int STRAIGHT = 3;
	int speedright = 0;
	int speedleft = 50;
	int timesrun = 0;
	int mode = SPIRAL;

	while(true)
	{

		if(mode == SPIRAL)
		{
			while(SensorValue(leftbutton) == 0)
			{
				motor[right] = speedright;
				motor[left] = speedleft;
				speedright = speedright + 2;
				speedleft = speedleft + 1;
				wait1Msec(500);
			}
			mode = WALLFOLLOW;
			timesrun = 0;
		}

		if(mode == WALLFOLLOW)
		{
		while(timesrun < 5)
			{
					motor[right] = -100;
					motor[left] = -100;
					wait1Msec(200);
					motor[right] = -100;
					motor[left] = -30;
					wait1Msec(700);

			while(SensorValue(leftbutton) == 0)
				{
					motor[right] = 100;
					motor[left] = 50;
					wait1Msec(100);
				}
				timesrun = timesrun + 1;
		 	}
		 	motor[right] = -100;
			motor[left] = -100;
			wait1Msec(1000);
			motor[right] = -100;
			motor[left] = -30;
			wait1Msec(1250);
			mode = STRAIGHT;
			resetMotorEncoder(right);
		}

		 if(mode == STRAIGHT)
		 {
			 	motor(right) = 100;
			  motor(left) = 100;
			  wait1Msec(100);

				if(SensorValue(leftbutton) == 1)
				{
					mode = WALLFOLLOW;
					timesrun = 0;
				}
				if(getMotorEncoder(right) > 3600)
				{
					mode = SPIRAL;
					speedleft = 50;
					speedright = 0;
				}

		  }

	}
}
