#pragma config(Sensor, S2,     button,         sensorNone)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(SensorValue(button) == 0)
	{
		int speedright = 0;
		int speedleft = 50;
		motor[right] = speedright;
		motor[left] = speedleft;
		speedright = speedright + 5;
		speedleft = speedleft + 2.5;
		wait1Msec(4000);
	}
	motor[right] = -100;
	motor[left] = 0;
	wait1Msec(250);
	while(SensorValue(button) == 0)
	{
		motor[right] = 50;
		motor[left] = 25;
		wait1Msec(100);
		motor[right] = 50;
		motor[left] = 0;
	}
	motor[right] = -100;
	motor[left] = 0;
	wait1Msec(250);
	while(SensorValue(button) == 0)
	{
		motor[right] = 50;
		motor[left] = 25;
		wait1Msec(100);
		motor[right] = 50;
		motor[left] = 0;
	}



int timesrun = 0;
	while(timesrun < 5)
	{
		while(SensorValue(button) == 0)
		{
			motor[right] = 100;
			motor[left] = 100;
		}
 		wait1Msec(500);
 		motor[right] = 0;
 		motor[left] = -100;
 		wait1Msec(1000);

  	while(SensorValue(button) == 0)
  	{
  		motor[right] = 100;
  		motor[left] = 100;
  	}
  	wait1Msec(500);
 		motor[right] = -100;
 		motor[left] = 0;
 		wait1Msec(1000);
  	timesrun = timesrun + 1;


	}





}
